copyright = "Â© Mantas Zdancius"
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "term"]
enableRobotsTXT = true
languageCode = "en"
timeZone = "Europe/Berlin"
timeout = "180s"
title = "Mantas Zdancius"

[module]
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

[params]
    defaultTheme = "dark"
    description = "Professional Photography Portfolio - I make hard things look easy. Technical depth meets human understanding."
    title = "Mantas Zdancius"

[params.author]
    email = "mantas.zdancius@me.com"
    name = "Mantas Zdancius"

[params.socialIcons]
    instagram = "https://www.instagram.com/mantas.tv"
    github = "https://github.com/Mantexas"
    linkedin = "https://www.linkedin.com/in/finetune"
    email = "mailto:mantas.zdancius@me.com"

[params.gallery]
    boxSpacing = 8
    targetRowHeight = 280
    targetRowHeightTolerance = 0.2

[outputs]
    home = ["HTML", "RSS"]
    page = ["HTML"]
