copyright = "Â© Mantas"
defaultContentLanguage = "en"
disableKinds = ["taxonomy"]
enableRobotsTXT = true
languageCode = "en"
timeZone = "Europe/Berlin"
timeout = "120s"
title = "Mantas"

[params]
    defaultTheme = "dark"
    description = "I make hard things look easy. Technical depth meets human understanding."
    title = "Mantas"
[params.author]
    email = "mantas.zdancius@me.com"
    name = "Mantas"
[params.socialIcons]
    # facebook = "https://www.facebook.com/"
    instagram = "https://www.instagram.com/mantas.tv"
    github = "https://github.com/Mantexas"
    # youtube = "https://www.youtube.com/"
    linkedin = "https://www.linkedin.com/in/finetune"
    #website = "https://example.com"
    #mastodon = "https://example.com"
    #pixelfed = "https://example.com"
    #mixcloud = "https://example.com"
    #flickr = "https://www.flickr.com"
    #500px = "https://500px"
    #whatsapp = "1234567890"
[params.gallery]
    #boxSpacing = 10
    #targetRowHeight = 288
    #targetRowHeightTolerance = 0.25

[outputs]
    home = ["HTML", "RSS"]
    page = ["HTML"]
