title = "Gallery"
languageCode = "en"
copyright = "Â© Your Name"
disableKinds = ["taxonomy", "term"]
defaultContentLanguage = "en"
enableRobotsTXT = true
timeZone = "Europe/Berlin"

[params]
  title = "My Gallery"
  description = "Example site for hugo-theme-gallery"
  defaultTheme = "dark"
  [params.author]
    name = "Your Name"
    email = "user@example.com"

[outputs]
  page = ["HTML"]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[imaging]
  resampleFilter = "CatmullRom"
  quality = 75
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.112.0"
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v2"

[menu]
  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/nicokaiser/hugo-theme-gallery/"
    weight = 3

[services]
  [services.rss]
    limit = 100
